SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;

ALTER TABLE `products` ADD `stock` double NOT NULL DEFAULT '0' AFTER `coupon`;
ALTER TABLE `products` ADD `minstock` double NOT NULL DEFAULT '0' AFTER `stock`;

SET FOREIGN_KEY_CHECKS=1;
COMMIT;
